# Numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = arr1.reshape(1,5)

In [6]:
print(arr2)

[[1 2 3 4 5]]


In [7]:
arr2 = np.array([[0,1,2,3,4],[5,6,7,8,9,]])

In [8]:
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
print(arr2.shape)

(2, 5)


In [10]:
arr3 = np.arange(0,10,2)
print(arr3)

[0 2 4 6 8]


In [11]:
arr4 = np.arange(0,10,2).reshape(5,1)
print(arr4)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [15]:
## Vectorized operation
v_arr1 = np.array([1,2,3,4,5])
v_arr2 = np.array([10,20,30,40,50])

### Element wise addtition
print('Addition:', v_arr1 + v_arr2)

### Element wise substraction
print('Substraction:', v_arr2 - v_arr1)

### Element wise multiplication
print('Multiplicatoin:', v_arr1 * v_arr2)

### Element wise division
print('Division:', v_arr2 / v_arr1)

Addition: [11 22 33 44 55]
Substraction: [ 9 18 27 36 45]
Multiplicatoin: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


In [16]:
## Universal functions (ufuncs)

arr = np.array([1,2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [17]:
## Array Slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
print(arr[0,0])

1


In [19]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [20]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [21]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [22]:
## Modifying array
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [23]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [24]:
## Statistical Concept -- Normalization

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data-mean) / std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [25]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
print("Mean:",mean)

median = np.median(data)
print("Median:",median)

std_dev = np.std(data)
print("Standard Deviation:",std_dev)

variance = np.var(data)
print("Variance:",variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [26]:
## Logical Opertations
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data > 5)

print(data[data > 5])

print(data[(data >= 5) & (data <=8)])


[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
